# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopo < Formula
  desc "Gopo"
  homepage ""
  version "0.1.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.1.7/gopo_Darwin_x86_64.tar.gz"
    sha256 "104eefcd29846c1dc20c6b1e120219e86dab520595eec36071d82d24626f658d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.1.7/gopo_Linux_x86_64.tar.gz"
    sha256 "76e36b567df2fcb8f2b435da6b0deea99632804faac47bcebd789eb75477bfd4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.1.7/gopo_Linux_arm64.tar.gz"
    sha256 "6d4036289b06db8ffebeae22d2f50f952f0204fd0bb7681c7263824da10ffc44"
  end

  def install
    system "rm -f #{bin}/gopo"
    bin.install "gopo"
  end

  def caveats; <<~EOS
    gopo -v
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/gopo --version"
  end
end
