# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopo < Formula
  desc "Gopo"
  homepage ""
  version "0.1.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.1.8/gopo_Darwin_x86_64.tar.gz"
    sha256 "551e1a37b34ef38e0c3295a390ed1009c6443b5eda6756ad0f2adb96aebcc7f2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.1.8/gopo_Linux_x86_64.tar.gz"
    sha256 "0e20f4848d719cd118a62652b96a9461bb308373a03773aa49522a3139d80d33"
  end

  def install
    system "rm -f #{bin}/gopo"
    bin.install "gopo"
  end

  def caveats; <<~EOS
    gopo -v
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/gopo --version"
  end
end
