# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopo < Formula
  desc "Gopo"
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.2.0/gopo_Darwin_x86_64.tar.gz"
    sha256 "b4a30b54d256b0e3f43b9a7be398695514bc34b6a440be0f0d3b28c88db8a5a4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/HYY-yu/gopo/releases/download/v0.2.0/gopo_Linux_x86_64.tar.gz"
    sha256 "a8dc0148f519c40c1b778cc82cb4d6ce45afc7c4c2a3819042d34bf9ce301918"
  end

  def install
    system "rm -f #{bin}/gopo"
    bin.install "gopo"
  end

  def caveats; <<~EOS
    gopo -v
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/gopo --version"
  end
end
